
export const quizlist = [
  {
    image: 'https://i.imgur.com/yBfBLvC.jpg',
    movie: 'The Shawshank Redemption',
    hints: ['Released: 1994', 'Starring: Tim Robbins', 'Based on a Stephen King Novel'],
    completed: false,
    activeDate: '2/2/2023',
    count: 0,
  },
  {
    image: 'https://i.imgur.com/SaYl9eV.jpg',
    movie: 'There Will Be Blood',
    hints: ['Released: 2007', 'Directed By: Paul Thomas Anderson', 'Starring: Daniel Day-Lewis'],
    completed: false,
    activeDate: '2/3/2023',
    count: 0,
  },
  {
    image: 'https://i.imgur.com/SZUrcDc.jpg',
    movie: 'Taxi Driver',
    hints: ['Released: 1976', 'Directed By: Martin Scorsese', 'Starring: Robert De Niro'],
    completed: false,
    activeDate: '2/4/2023',
    count: 0,
  },
  {
    image: 'https://i.imgur.com/xYjifnJ.jpg',
    movie: 'Shutter Island',
    hints: ['Released: 2010', 'Directed By: Martin Scorsese', 'Starring: Leonardo DiCaprio'],
    completed: false,
    activeDate: '2/1/2023',
    count: 0,
  },
  {
    image: 'https://i.imgur.com/eJjz4lr.jpg',
    movie: 'Django Unchained',
    hints: ['Released: 2012', 'Directed By: Quentin Tarantino', 'Starring: Jamie Foxx'],
    completed: false,
    activeDate: '1/31/2023',
    count: 0,
  },
  {
    image: 'https://i.imgur.com/5In1vNH.jpg',
    movie: 'The Godfather',
    hints: ['Released: 1972', 'Based on a Novel by Mario Puzo', 'Directed by Francis Ford Coppola'],
    completed: false,
    activeDate: '2/5/2023',
    count: 0,
  },
]

export const answerKey = [
  // { answer: 'There Will Be Blood' },
  // { answer: 'Taxi Driver' },
  // { answer: 'Shutter Island' },
  // { answer: 'Gone Girl' },
  // { answer: 'Full Metal Jacket' },
  // { answer: 'The Aviator' },
  // { answer: 'Django Unchained' },
  // { answer: 'The Girl With The Dragon Tattoo' },
  // { answer: 'The Northman' },
  // { answer: 'The Darjeeling Limited' },
  // { answer: 'No Country For Old Men' },
  // { answer: 'Midsommar' },
  // { answer: 'Parasite' },
  // { answer: 'The Shawshank Redemption' },
  // { answer: 'The Godfather' },
]

let movieList = [
  "The Shawshank Redemption (1994)",
  "The Godfather (1972)",
  "The Godfather: Part II (1974)",
  "The Dark Knight (2008)",
  "12 Angry Men (1957)",
  "Schindler's List (1993)",
  "The Lord of the Rings: The Return of the King (2003)",
  "Pulp Fiction (1994)",
  "The Good, the Bad and the Ugly (1966)",
  "The Lord of the Rings: The Fellowship of the Ring (2001)",
  "Forrest Gump (1994)",
  "Inception (2010)",
  "The Lord of the Rings: The Two Towers (2002)",
  "Star Wars: Episode V - The Empire Strikes Back (1980)",
  "The Matrix (1999)",
  "Goodfellas (1990)",
  "One Flew Over the Cuckoo's Nest (1975)",
  "Se7en (1995)",
  "Seven Samurai (1954)",
  "City of God (2002)",
  "The Silence of the Lambs (1991)",
  "It's a Wonderful Life (1946)",
  "The Usual Suspects (1995)",
  "Léon: The Professional (1994)",
  "Life is Beautiful (1997)",
  "Saving Private Ryan (1998)",
  "Interstellar (2014)",
  "American History X (1998)",
  "The Green Mile (1999)",
  "Terminator 2: Judgment Day (1991)",
  "Whiplash (2014)",
  "Modern Times (1936)",
  "The Departed (2006)",
  "Gladiator (2000)",
  "Back to the Future (1985)",
  "Psycho (1960)",
  "The Prestige (2006)",
  "The Lion King (1994)",
  "The Intouchables (2011)",
  "The Pianist (2002)",
  "The Lives of Others (2006)",
  "The Shining (1980)",
  "American Beauty (1999)",
  "Once Upon a Time in the West (1968)",
  "The Sting (1973)",
  "Alien (1979)",
  "Django Unchained (2012)",
  "Whiplash (2014)",
  "The Silence (1963)",
  "Lawrence of Arabia (1962)",
  "The Great Dictator (1940)",
  "Amélie (2001)",
  "The Grave of the Fireflies (1988)",
  "Cinema Paradiso (1988)",
  "The Usual Suspects (1995)",
  "Spirited Away (2001)",
  "Grave of the Fireflies (1988)",
  "City Lights (1931)",
  "To Kill a Mockingbird (1962)",
  "Full Metal Jacket (1987)",
  "Double Indemnity (1944)",
  "Taxi Driver (1976)",
  "Singin' in the Rain (1952)",
  "L.A. Confidential (1997)",
  "The Apartment (1960)",
  "Das Boot (1981)",
  "Vertigo (1958)",
  "The Third Man (1949)",
  "Eternal Sunshine of the Spotless Mind (2004)",
  "Requiem for a Dream (2000)",
  "Apocalypse Now (1979)",
  "Good Will Hunting (1997)",
  "The Kid (1921)",
]
console.log(movieList.length)